export const Translate = {
    WhyUs: [
        {
          id: "fr",
          title:"Pourquoi Touil Digicom",
          section1_title:`NOTRE CRÉATIVITÉ QUI REPOUSSE LES LIMITES`,
          section1_text:`Lorsque vous recherchez une agence de communication, il est essentiel de trouver un partenaire fiable et compétent qui comprend vos besoins et peut vous aider à atteindre vos objectifs commerciaux. Chez Conceptify, nous sommes convaincus d'être le choix idéal pour votre entreprise.`,
          RAPIDITÉ:'RAPIDITÉ',
          RÉPONSE:'RÉPONSE EN TEMPS RÉEL',
          EFFICACITÉ:'EFFICACITÉ ',
          FLEXIBILITÉ:'FLEXIBILITÉ ',
          counter1:'Clients Nous Font Confiance',
          counter2:'Partenaires Créatifs',
          counter3:'Litres de cafés consommés',
          counter4:'Fous rires',
        },
        {
          id: "ar",
          title:"لماذا تويل ديجيكوم",
          section1_title:`إبداعنا الذي يتخطى الحدود`,
          section1_text:`عند البحث عن وكالة اتصالات، من الضروري العثور على شريك موثوق به وواسع المعرفة يفهم احتياجاتك ويمكنه مساعدتك في تحقيق أهداف عملك. في Conceptify، نحن واثقون من أننا الخيار الأمثل لعملك.`,
          RAPIDITÉ:'سرعة',
          RÉPONSE:'الاستجابة في الوقت الحقيقي',
          EFFICACITÉ:'كفاءة',
          FLEXIBILITÉ:'المرونة',
          counter1:'العملاء يثقون بنا',
          counter2:'الشركاء مبدعون',
          counter3:'لتر من القهوة المستهلكة',
          counter4:'ضحك بجنون',
        },
      ],
    };